### PR TITLE
Add a Helper Plugin so other plugins can use this plugin for there Notifications

### PR DESCRIPTION
**Pull request by Unbekannt1998**
This PR refactors the methods in `action.php` into a helper plugin, so other plugins can use those methods to send their own notifications (such as for approvals or discussion comments). This PR does not change the normal behavior of this plugin.

### CODE REVIEW

**Comment by Rainbow-Spike** [comment]
This commit don't work for my site… even after fixing [this string](https://github.com/zteeed/dokuwiki-discord-notifier/pull/5/files#diff-f83b2f0ae7b33833c8a01a1389b9e978cb2879c7f9eb94622d770c778b2fa1b9R27) to `attic_write ( $event )`

**Comment by Unbekannt1998** [comment]
Can you go in more detail what does not work? 
Because I have this working on multiple sites even with a plugin that uses the new helper plugin.

**Comment by Rainbow-Spike** [comment]
After save I get whte screen, F5 it, see duplicate version detection screen, choose to save my version and go in my Discord's channel for notices - there I see no fresh news.

**Comment by Rainbow-Spike** [comment]
Ouch. Now I recheck files not by rewriting my workfiles from diff lines but by copy-pasting of raw files. Sorry, it works.

**Comment by Rainbow-Spike** [comment]
My server logs is clear, [it works](http://screenshot.ru/ceaeb47d1043d8fe8a97fcf7c8bb5ab0.png)

**Comment by zteeed** [comment]
Thanks @Rainbow-Spike !

**Pull request merged**
